import { Inter} from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Toaster } from "sonner";
import './globals.css'
import Footer from "@/components/footer";

const inter= Inter({
  subset:["latin"]
});

export const metadata = {
  title: "AI career coach",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
    <html lang="en" 
     className="dark"
     suppressHydrationWarning>
      <body
        className={`${inter.className}`}
      >
         <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {/* header */}
            <Header/>
            <main className="min-h-screen">{children}</main>
            <Toaster richColors />
            {/* footer */}
            <Footer/>
          </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
